※ **본 자료는 sk-learn에서 제공하는 자료 설명을 가공한 것입니다.**

![iris1](https://miro.medium.com/max/1350/0*Uw37vrrKzeEWahdB)

![iris2](https://miro.medium.com/max/1650/0*7H_gF1KnslexnJ3s)

The iris dataset is a classic and very easy multi-class classification dataset.

|Classes|Samples per class|Dimensionality|Features|
|:---:|:--:|:---:|:---:|
|3 | 50 | 4 | real, positive |

### 데이터 로딩방법 

In [1]:
def load_iris(return_X_y=False):
    module_path = dirname(__file__)
    data, target, target_names = load_data(module_path, 'iris.csv')
    iris_csv_filename = join(module_path, 'data', 'iris.csv')

    with open(join(module_path, 'descr', 'iris.rst')) as rst_file:
        fdescr = rst_file.read()

    if return_X_y:
        return data, target

    return Bunch(data=data, target=target,
                 target_names=target_names,
                 DESCR=fdescr,
                 feature_names=['sepal length (cm)', 'sepal width (cm)',
                                'petal length (cm)', 'petal width (cm)'],
                 filename=iris_csv_filename)

In [2]:
from sklearn.datasets import load_iris

#### 1) return_X_y = False

In [3]:
iris = load_iris(return_X_y = False)

for k, v in iris.items() :
    if (k == "DESCR") | (k == "filename") :
        print("[{}]: \n{}\n========================================================================================================".format(k, v))
    else : print("[{}]: \n{}\n========================================================================================================".format(k, v[:5]))

[data]: 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[target]: 
[0 0 0 0 0]
[target_names]: 
['setosa' 'versicolor' 'virginica']
[DESCR]: 
.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.

In [4]:
print("default로 불러올 때: {}".format(type(iris)))

default로 불러올 때: <class 'sklearn.utils.Bunch'>


> [Bunch](https://pypi.org/project/bunch/)란? : dictionary와 동일한데, <kbd>.</kbd>으로도 값을 불러올 수 있다.  

#### 2) return_X_y = True

In [5]:
iris = load_iris(return_X_y = True)
type(iris), len(iris)

(tuple, 2)

In [6]:
x, y = load_iris(return_X_y = True)
type(x), type(y), len(x), len(y)

(numpy.ndarray, numpy.ndarray, 150, 150)